package com.verbtrainer.smart;
import com.fasterxml.jackson.databind.ObjectMapper;import com.verbtrainer.conjugation.*;import com.verbtrainer.dictionary.*;import com.verbtrainer.learning.*;
import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;import java.util.stream.*;
@Service public class DefaultSmartQuestionSelector implements SmartQuestionSelector{
 private final VerbRepository verbs;private final StudyRepository studies;private final KnowledgePointRepository mastery;private final TrainingQuestionRepository recent;private final TrainingSessionRepository sessions;private final ConjugationService conjugator;private final JlptTrainingPolicy policy;private final KnowledgePointTagger tagger;private final SmartSelectionProperties cfg;private final ObjectMapper json;private final ConjugationLabelProvider labels;
 public DefaultSmartQuestionSelector(VerbRepository verbs,StudyRepository s,KnowledgePointRepository m,TrainingQuestionRepository r,TrainingSessionRepository ss,ConjugationService c,JlptTrainingPolicy p,KnowledgePointTagger t,SmartSelectionProperties cfg,ObjectMapper j,ConjugationLabelProvider labels){this.verbs=verbs;studies=s;mastery=m;recent=r;sessions=ss;conjugator=c;policy=p;tagger=t;this.cfg=cfg;json=j;this.labels=labels;}
 @Transactional public TrainingSessionPlan createPlan(CreateTrainingSessionRequest req){validate(req);var levelVerbs=verbs.findByJlptLevelOrderByCommonRankAscIdAsc(req.jlptLevel(),PageRequest.of(0,500));var types=effectiveConjugations(req);var qtypes=effectiveQuestionTypes(req);var studyMap=studies.findAll().stream().collect(Collectors.toMap(x->x.verbId+"|"+x.form,x->x,(a,b)->a));var masteryMap=mastery.findAll().stream().collect(Collectors.toMap(x->x.knowledgePointKey,x->x,(a,b)->a));var recentKeys=recent.findTop30ByOrderByIdDesc().stream().map(q->q.verbId+"|"+q.conjugationType+"|"+q.questionType).collect(Collectors.toSet());
  List<Candidate>pool=new ArrayList<>();for(var v:levelVerbs)for(var ct:types)for(var qt:qtypes){String lemma=trainingLemma(v),reading=trainingReading(v);var result=conjugator.conjugate(lemma,v.verbClass).stream().filter(x->x.form()==ct.form).findFirst().orElse(null);if(result==null)continue;var keys=tagger.tag(v,ct,qt);var si=studyMap.get(v.id+"|"+ct.form.name());boolean due=si!=null&&!si.nextReview.isAfter(LocalDateTime.now());boolean fresh=si==null;double weak=keys.stream().map(masteryMap::get).filter(Objects::nonNull).mapToDouble(x->100-x.masteryScore).max().orElse(50);double commonness=Math.max(0,101-Objects.requireNonNullElse(v.commonRank,9999))*cfg.commonnessWeight;double score=50+commonness+(due&&req.prioritizeDueReview()?cfg.dueReviewWeight:0)+(req.prioritizeWeakness()?weak/100*cfg.weaknessWeight:0)+(si==null?cfg.noveltyWeight:si.errorCount*cfg.historicalErrorWeight/3.0);if(recentKeys.contains(v.id+"|"+ct+"|"+qt))score-=cfg.recentRepetitionPenalty;if(keys.stream().map(masteryMap::get).filter(Objects::nonNull).anyMatch(x->x.masteryScore>=cfg.masteredScoreThreshold&&x.correctStreak>=cfg.masteredCorrectStreak))score-=cfg.masteredPenalty;
   if(req.mode()==TrainingMode.WRONG_ONLY&&(si==null||si.errorCount==0))continue;if(req.mode()==TrainingMode.DUE_REVIEW&&!due)continue;if(req.mode()==TrainingMode.NEW_WORDS&&!fresh)continue;if(req.mode()==TrainingMode.RANDOM)score=Math.floorMod(Objects.hash(v.id,ct,qt,System.currentTimeMillis()/60000),1000);pool.add(new Candidate(v,lemma,reading,ct,qt,result,keys,score,due,fresh,si));}
  pool.sort(Comparator.comparingDouble(Candidate::score).reversed().thenComparing(c->c.v.id));var selected=selectDiverse(pool,req.questionCount());var session=new TrainingSession(req.jlptLevel(),req.mode(),req.questionCount());int limit=selected.size();for(var c:selected){var q=build(c,req.showReading());q.session=session;session.questions.add(q);}session.actualCount=limit;if(limit<req.questionCount())session.shortageReason="当前等级可用的不重复题目只有 "+limit+" 道";sessions.save(session);return new TrainingSessionPlan(session);}
 private TrainingQuestion build(Candidate c,boolean showReading){var q=new TrainingQuestion();q.verbId=c.v.id;q.questionType=c.qt;q.conjugationType=c.ct;q.dictionaryForm=c.lemma;q.reading=showReading?c.reading:null;q.correctAnswer=c.result.value();q.knowledgePointKeys=String.join("\n",c.keys);q.priorityScore=c.score;List<Map<String,String>>reasons=new ArrayList<>();if(c.due)reasons.add(reason(SelectionReason.DUE_REVIEW,"这项复习已经到期"));if(c.study!=null&&c.study.errorCount>0)reasons.add(reason(SelectionReason.FREQUENTLY_WRONG_VERB,"你曾在这个动词上答错 "+c.study.errorCount+" 次"));if(c.fresh)reasons.add(reason(SelectionReason.NEW_WORD,"这是当前等级尚未练习的新词"));if(reasons.isEmpty())reasons.add(reason(SelectionReason.MAINTENANCE_REVIEW,"用于维持已经学过的活用规则"));try{q.selectionReasons=json.writeValueAsString(reasons);}catch(Exception e){q.selectionReasons="[]";}
  String formName=labels.getLabel(c.ct).displayName();switch(c.qt){case CONJUGATION_TO_DICTIONARY->{q.prompt="「"+c.result.value()+"」的原形是什么？";q.correctAnswer=c.lemma;}case VERB_CLASS->{q.prompt="「"+c.lemma+"」属于哪一类动词？";q.correctAnswer=c.v.verbClass.name();q.optionsJson=toJson(List.of("GODAN","ICHIDAN","SURU","KURU"));}case TRUE_FALSE->{boolean truth=Math.floorMod(Objects.hash(c.v.id,c.ct),2)==0;String shown=truth?c.result.value():wrong(c);q.prompt="判断：「"+c.lemma+"」的"+formName+"是「"+shown+"」。";q.correctAnswer=truth?"正确":"错误";q.optionsJson=toJson(List.of("正确","错误"));}case MULTIPLE_CHOICE_CONJUGATION->{q.prompt="选择「"+c.lemma+"」正确的"+formName+"。";q.optionsJson=toJson(options(c));}case CONTEXT_SELECTION->{q.prompt="选择最合适的形式填空：「"+c.lemma+"」→（　）";q.optionsJson=toJson(options(c));}default->q.prompt="请输入「"+c.lemma+"」的"+formName+"。";}return q;}
 private List<String>options(Candidate c){LinkedHashSet<String>x=new LinkedHashSet<>();x.add(c.result.value());x.add(wrong(c));x.add(c.lemma.substring(0,Math.max(1,c.lemma.length()-1))+"いて");x.add(c.lemma.substring(0,Math.max(1,c.lemma.length()-1))+"って");for(var r:conjugator.conjugate(c.lemma,c.v.verbClass))if(x.size()<4)x.add(r.value());return x.stream().filter(s->!s.isBlank()).limit(4).toList();}
 private String wrong(Candidate c){String v=c.lemma;return v.substring(0,Math.max(1,v.length()-1))+"みて";}
 private String trainingLemma(VerbEntry v){return v.verbClass==VerbClass.SURU&&!v.lemma.endsWith("する")?v.lemma+"する":v.lemma;}
 private String trainingReading(VerbEntry v){return v.verbClass==VerbClass.SURU&&!v.reading.endsWith("する")?v.reading+"する":v.reading;}
 private List<Candidate>selectDiverse(List<Candidate>pool,int count){Map<Long,ArrayDeque<Candidate>>byVerb=new LinkedHashMap<>();for(var c:pool)byVerb.computeIfAbsent(c.v.id,id->new ArrayDeque<>()).add(c);List<Candidate>out=new ArrayList<>();boolean added=true;while(out.size()<count&&added){added=false;for(var queue:byVerb.values()){if(out.size()>=count)break;var candidate=queue.poll();if(candidate!=null){out.add(candidate);added=true;}}}return out;}
 private Map<String,String>reason(SelectionReason c,String m){return Map.of("code",c.name(),"messageZh",m);}private String toJson(Object o){try{return json.writeValueAsString(o);}catch(Exception e){return"[]";}}
 private Set<ConjugationType>effectiveConjugations(CreateTrainingSessionRequest r){return r.conjugationTypes()==null||r.conjugationTypes().isEmpty()?policy.allowedConjugationTypes(r.jlptLevel()):r.conjugationTypes();}
 private Set<QuestionType>effectiveQuestionTypes(CreateTrainingSessionRequest r){return r.questionTypes()==null||r.questionTypes().isEmpty()?policy.allowedQuestionTypes(r.jlptLevel()):r.questionTypes();}
 private void validate(CreateTrainingSessionRequest r){if(!Set.of(10,20,30,50).contains(r.questionCount()))throw new IllegalArgumentException("questionCount 只允许 10、20、30、50");if(r.mode()==TrainingMode.CUSTOM&&((r.questionTypes()==null||r.questionTypes().isEmpty())&&(r.conjugationTypes()==null||r.conjugationTypes().isEmpty())))throw new IllegalArgumentException("CUSTOM 模式必须选择题型或活用类型");if(r.mode()!=TrainingMode.CUSTOM&&r.conjugationTypes()!=null&&!policy.allowedConjugationTypes(r.jlptLevel()).containsAll(r.conjugationTypes()))throw new IllegalArgumentException(r.jlptLevel()+" 不允许请求中的越级活用；请使用 CUSTOM 模式");if(r.mode()!=TrainingMode.CUSTOM&&r.questionTypes()!=null&&!policy.allowedQuestionTypes(r.jlptLevel()).containsAll(r.questionTypes()))throw new IllegalArgumentException(r.jlptLevel()+" 不允许请求中的题型");}
 private record Candidate(VerbEntry v,String lemma,String reading,ConjugationType ct,QuestionType qt,ConjugationResult result,List<String>keys,double score,boolean due,boolean fresh,StudyItem study){}
}
