package com.verbtrainer.smart;
import com.verbtrainer.dictionary.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
@Service public class JlptLevelImporter{
 private final VerbRepository verbs;private final JlptVocabularyRepository levels;public JlptLevelImporter(VerbRepository v,JlptVocabularyRepository l){verbs=v;levels=l;}
 public record ImportReport(int rows,int imported,int unchanged,List<String>ambiguous,List<String>unmatched,List<String>invalid){}
 @Transactional public ImportReport importFile(InputStream input)throws IOException{List<String>lines=new BufferedReader(new InputStreamReader(input,StandardCharsets.UTF_8)).lines().toList();if(lines.isEmpty())throw new IllegalArgumentException("文件为空");char sep=lines.get(0).contains("\t")?'\t':',';String[]h=split(lines.get(0),sep);Map<String,Integer>cols=new HashMap<>();for(int i=0;i<h.length;i++)cols.put(h[i].strip(),i);for(String required:List.of("dictionary_form","reading","jlpt_level"))if(!cols.containsKey(required))throw new IllegalArgumentException("缺少列："+required);
  int imported=0,unchanged=0;List<String>a=new ArrayList<>(),u=new ArrayList<>(),bad=new ArrayList<>();for(int n=1;n<lines.size();n++){if(lines.get(n).isBlank())continue;String[]x=split(lines.get(n),sep);try{String lemma=get(x,cols,"dictionary_form").strip(),reading=get(x,cols,"reading").strip();if(reading.isEmpty()||!reading.matches("[ぁ-ゖァ-ヺー]+"))throw new IllegalArgumentException("读音必须为假名");JlptLevel level=JlptLevel.valueOf(get(x,cols,"jlpt_level").strip());var matches=verbs.findByLemmaAndReading(lemma,reading);if(matches.isEmpty()){u.add("第"+(n+1)+"行："+lemma+"/"+reading);continue;}if(matches.size()>1){a.add("第"+(n+1)+"行："+lemma+"/"+reading+" 候选="+matches.size());continue;}var source=parse(x,cols,"source",JlptLevelSource.SEED_DATA,JlptLevelSource.class);var confidence=parse(x,cols,"confidence",DataConfidence.MEDIUM,DataConfidence.class);var existing=levels.findByDictionaryEntryIdAndJlptLevel(matches.get(0).id,level);if(existing.isPresent()){unchanged++;}else{levels.save(new JlptVocabularyLevel(matches.get(0).id,level,source,confidence));imported++;}}catch(Exception e){bad.add("第"+(n+1)+"行："+e.getMessage());}}
  return new ImportReport(lines.size()-1,imported,unchanged,a,u,bad);}
 private String[]split(String s,char sep){return s.split(java.util.regex.Pattern.quote(String.valueOf(sep)),-1);}private String get(String[]x,Map<String,Integer>c,String k){int i=c.get(k);return i<x.length?x[i]:"";}
 private <T extends Enum<T>>T parse(String[]x,Map<String,Integer>c,String k,T d,Class<T>t){if(!c.containsKey(k)||get(x,c,k).isBlank())return d;return Enum.valueOf(t,get(x,c,k).strip());}
}
