package com.verbtrainer.smart; public enum KnowledgePointType { VERB,VERB_CLASS,CONJUGATION_TYPE,GODAN_ENDING_RULE,EXCEPTION_VERB,SURU_COMPOUND,KURU_READING_CHANGE,REVERSE_RECOGNITION,CONTEXT_USAGE }
