package com.verbtrainer.smart;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.verbtrainer.conjugation.*;import com.verbtrainer.learning.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.stream.*;
@Service public class TrainingSessionService{
 private final SmartQuestionSelector selector;private final TrainingSessionRepository sessions;private final TrainingQuestionRepository questions;private final StudyRepository study;private final KnowledgePointService knowledge;private final ObjectMapper json;
 public TrainingSessionService(SmartQuestionSelector s,TrainingSessionRepository ss,TrainingQuestionRepository q,StudyRepository st,KnowledgePointService k,ObjectMapper j){selector=s;sessions=ss;questions=q;study=st;knowledge=k;json=j;}
 @Transactional public Map<String,Object>create(CreateTrainingSessionRequest req){var s=selector.createPlan(req).session();return sessionResponse(s);}
 @Transactional public Map<String,Object>answer(Long sessionId,Long questionId,String raw){var q=questions.findByIdAndSessionId(questionId,sessionId).orElseThrow(()->new NoSuchElementException("题目不属于当前训练"));if(q.answeredAt!=null)throw new IllegalStateException("这道题已经提交过，统计不会重复累计");String normalized=normalize(raw);boolean ok=normalize(q.correctAnswer).equals(normalized);q.submittedAnswer=normalized;q.correct=ok;q.answeredAt=Instant.now();questions.save(q);var keys=List.of(q.knowledgePointKeys.split("\\n"));knowledge.update(keys,ok,q.answeredAt);var item=study.findByVerbIdAndForm(q.verbId,q.conjugationType.form.name()).orElseGet(()->new StudyItem(q.verbId,q.conjugationType.form.name()));item.review(ok);study.save(item);return Map.of("correct",ok,"normalizedAnswer",normalized,"correctAnswer",q.correctAnswer,"explanation",explanation(q),"knowledgePointsUpdated",keys,"nextReviewAt",item.nextReview);}
 @Transactional(readOnly=true)public Map<String,Object>summary(Long id){var s=sessions.findById(id).orElseThrow();var done=s.questions.stream().filter(q->q.answeredAt!=null).toList();long correct=done.stream().filter(q->Boolean.TRUE.equals(q.correct)).count();var out=new LinkedHashMap<String,Object>();out.put("sessionId",s.id);out.put("jlptLevel",s.jlptLevel);out.put("totalQuestions",s.actualCount);out.put("completedCount",done.size());out.put("correctCount",correct);out.put("accuracy",done.isEmpty()?0:Math.round(correct*1000.0/done.size())/10.0);out.put("byQuestionType",rates(done,q->q.questionType.name()));out.put("byConjugationType",rates(done,q->q.conjugationType.name()));out.put("weakestKnowledgePoints",weak(done));out.put("wrongVerbs",done.stream().filter(q->!Boolean.TRUE.equals(q.correct)).map(q->q.dictionaryForm).distinct().toList());out.put("recommendation",correct<done.size()*.7?"继续当前等级的薄弱规则专项":"可继续当前等级，或尝试下一等级");return out;}
 private Map<String,Object>sessionResponse(TrainingSession s){List<Map<String,Object>>qs=new ArrayList<>();for(var q:s.questions){var m=new LinkedHashMap<String,Object>();m.put("questionId",q.id);m.put("questionType",q.questionType);m.put("dictionaryForm",q.dictionaryForm);m.put("reading",q.reading);m.put("conjugationType",q.conjugationType);m.put("prompt",q.prompt);m.put("options",parseList(q.optionsJson));m.put("selectionReasons",parseReasons(q.selectionReasons));qs.add(m);}var out=new LinkedHashMap<String,Object>();out.put("sessionId",s.id);out.put("jlptLevel",s.jlptLevel);out.put("mode",s.mode);out.put("requestedCount",s.requestedCount);out.put("actualCount",s.actualCount);out.put("shortageReason",s.shortageReason);out.put("questions",qs);return out;}
 private String explanation(TrainingQuestion q){return switch(q.conjugationType){case TE,PAST->"答案由本地规则引擎计算。五段动词需按词尾音便，一段动词去「る」后接相应形式。";default->"答案由本地活用策略计算；请查看该动词的变化步骤巩固规则。";};}
 private List<String>weak(List<TrainingQuestion>x){Map<String,long[]>m=new HashMap<>();for(var q:x)for(String k:q.knowledgePointKeys.split("\\n")){var a=m.computeIfAbsent(k,z->new long[2]);a[0]++;if(!Boolean.TRUE.equals(q.correct))a[1]++;}return m.entrySet().stream().sorted(Comparator.<Map.Entry<String,long[]>>comparingLong(e->e.getValue()[1]).reversed()).limit(5).map(Map.Entry::getKey).toList();}
 private Map<String,Map<String,Object>>rates(List<TrainingQuestion>x,java.util.function.Function<TrainingQuestion,String>key){Map<String,List<TrainingQuestion>>g=x.stream().collect(Collectors.groupingBy(key));Map<String,Map<String,Object>>out=new TreeMap<>();g.forEach((k,v)->{long c=v.stream().filter(q->Boolean.TRUE.equals(q.correct)).count();out.put(k,Map.of("attempts",v.size(),"correct",c,"accuracy",Math.round(c*1000.0/v.size())/10.0));});return out;}
 private String normalize(String s){return s==null?"":s.strip().replace(" ","").replace("　","");}
 private List<String>parseList(String s){try{return s==null?List.of():json.readValue(s,new TypeReference<>(){});}catch(Exception e){return List.of();}}
 private List<Map<String,String>>parseReasons(String s){try{return json.readValue(s,new TypeReference<>(){});}catch(Exception e){return List.of();}}
}
