package com.verbtrainer.smart;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.verbtrainer.conjugation.*;import com.verbtrainer.learning.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.stream.*;
@Service public class TrainingSessionService{
 private final SmartQuestionSelector selector;private final TrainingSessionRepository sessions;private final TrainingQuestionRepository questions;private final StudyRepository study;private final KnowledgePointService knowledge;private final ObjectMapper json;private final ConjugationLabelProvider labels;private final ConjugationService conjugator;private final com.verbtrainer.dictionary.VerbRepository verbs;
 public TrainingSessionService(SmartQuestionSelector s,TrainingSessionRepository ss,TrainingQuestionRepository q,StudyRepository st,KnowledgePointService k,ObjectMapper j,ConjugationLabelProvider labels,ConjugationService conjugator,com.verbtrainer.dictionary.VerbRepository verbs){selector=s;sessions=ss;questions=q;study=st;knowledge=k;json=j;this.labels=labels;this.conjugator=conjugator;this.verbs=verbs;}
 @Transactional public Map<String,Object>create(CreateTrainingSessionRequest req){var s=selector.createPlan(req).session();return sessionResponse(s);}
 @Transactional public Map<String,Object>answer(Long sessionId,Long questionId,String raw){var q=questions.findByIdAndSessionId(questionId,sessionId).orElseThrow(()->new NoSuchElementException("题目不属于当前训练"));if(q.answeredAt!=null)throw new IllegalStateException("这道题已经提交过，统计不会重复累计");String normalized=normalize(raw);boolean ok=normalize(q.correctAnswer).equals(normalized);q.submittedAnswer=normalized;q.correct=ok;q.answeredAt=Instant.now();q.mistakeType=ok?null:classifyMistake(q,normalized);questions.save(q);var keys=List.of(q.knowledgePointKeys.split("\\n"));knowledge.update(keys,ok,q.answeredAt);var item=study.findByVerbIdAndForm(q.verbId,q.conjugationType.form.name()).orElseGet(()->new StudyItem(q.verbId,q.conjugationType.form.name()));item.review(ok);study.save(item);var label=labels.getLabel(q.conjugationType);var result=conjugationResult(q);String change=q.questionType==QuestionType.CONJUGATION_TO_DICTIONARY&&result!=null?result.value()+" → "+q.correctAnswer:q.dictionaryForm+" → "+q.correctAnswer;var out=new LinkedHashMap<String,Object>();out.put("correct",ok);out.put("normalizedAnswer",normalized);out.put("correctAnswer",q.correctAnswer);out.put("dictionaryForm",q.dictionaryForm);out.put("change",change);out.put("conjugationType",q.conjugationType);out.put("japaneseName",label.japaneseName());out.put("chineseName",label.chineseName());out.put("displayName",label.displayName());out.put("labelExplanation",label.explanation());out.put("steps",result==null?List.of():result.steps());out.put("explanation",explanation(q,result));out.put("knowledgePoint",q.knowledgePoint==null?null:q.knowledgePoint.name);out.put("mistakeType",q.mistakeType);out.put("knowledgePointsUpdated",keys.stream().map(this::displayKnowledgePoint).toList());out.put("nextReviewAt",item.nextReview);return out;}
 @Transactional(readOnly=true)public Map<String,Object>summary(Long id){var s=sessions.findById(id).orElseThrow();var done=s.questions.stream().filter(q->q.answeredAt!=null).toList();long correct=done.stream().filter(q->Boolean.TRUE.equals(q.correct)).count();var out=new LinkedHashMap<String,Object>();out.put("sessionId",s.id);out.put("jlptLevel",s.jlptLevel);out.put("totalQuestions",s.actualCount);out.put("completedCount",done.size());out.put("correctCount",correct);out.put("accuracy",done.isEmpty()?0:Math.round(correct*1000.0/done.size())/10.0);out.put("byQuestionType",rates(done,q->q.questionType.name()));out.put("byConjugationType",rates(done,q->labels.getLabel(q.conjugationType).chineseName()));out.put("weakestKnowledgePoints",weak(done));out.put("wrongVerbs",done.stream().filter(q->!Boolean.TRUE.equals(q.correct)).map(q->q.dictionaryForm).distinct().toList());out.put("recommendation",correct<done.size()*.7?"继续当前等级的薄弱规则专项":"可继续当前等级，或尝试下一等级");return out;}
 private Map<String,Object>sessionResponse(TrainingSession s){List<Map<String,Object>>qs=new ArrayList<>();for(var q:s.questions){var label=labels.getLabel(q.conjugationType);var m=new LinkedHashMap<String,Object>();m.put("questionId",q.id);m.put("questionType",q.questionType);m.put("dictionaryForm",q.dictionaryForm);m.put("reading",q.reading);m.put("conjugationType",q.conjugationType);m.put("japaneseName",label.japaneseName());m.put("chineseName",label.chineseName());m.put("displayName",label.displayName());m.put("labelExplanation",label.explanation());m.put("prompt",q.prompt);m.put("options",parseList(q.optionsJson));m.put("selectionReasons",parseReasons(q.selectionReasons));qs.add(m);}var out=new LinkedHashMap<String,Object>();out.put("sessionId",s.id);out.put("jlptLevel",s.jlptLevel);out.put("mode",s.mode);out.put("knowledgePointCode",s.knowledgePoint==null?null:s.knowledgePoint.code);out.put("knowledgePointName",s.knowledgePoint==null?null:s.knowledgePoint.name);out.put("requestedCount",s.requestedCount);out.put("actualCount",s.actualCount);out.put("shortageReason",s.shortageReason);out.put("questions",qs);return out;}
 private ConjugationResult conjugationResult(TrainingQuestion q){var verb=verbs.findById(q.verbId).orElse(null);if(verb==null)return null;return conjugator.conjugate(q.dictionaryForm,verb.verbClass).stream().filter(r->r.form()==q.conjugationType.form).findFirst().orElse(null);}
 private String explanation(TrainingQuestion q,ConjugationResult result){if(result!=null&&!result.steps().isEmpty())return String.join("；",result.steps())+"。";return switch(q.conjugationType){case TE,PAST->"五段动词需按词尾音便，一段动词去「る」后接相应形式。";default->"答案由本地活用策略计算，请根据变化步骤巩固规则。";};}
 private List<String>weak(List<TrainingQuestion>x){Map<String,long[]>m=new HashMap<>();for(var q:x)for(String k:q.knowledgePointKeys.split("\\n")){var a=m.computeIfAbsent(k,z->new long[2]);a[0]++;if(!Boolean.TRUE.equals(q.correct))a[1]++;}return m.entrySet().stream().sorted(Comparator.<Map.Entry<String,long[]>>comparingLong(e->e.getValue()[1]).reversed()).limit(5).map(Map.Entry::getKey).map(this::displayKnowledgePoint).toList();}
 private String displayKnowledgePoint(String key){if(key.startsWith("CONJUGATION_TYPE:")){try{return labels.getLabel(ConjugationType.valueOf(key.substring("CONJUGATION_TYPE:".length()))).chineseName();}catch(Exception ignored){return"活用规则";}}if(key.startsWith("REVERSE_RECOGNITION:"))return"活用还原原形";if(key.startsWith("GODAN_ENDING_RULE:"))return"五段动词词尾音便";if(key.startsWith("VERB_CLASS:"))return"动词类别："+key.substring("VERB_CLASS:".length());if(key.startsWith("VERB:"))return"动词："+key.substring("VERB:".length());if(key.startsWith("EXCEPTION_VERB:"))return"特殊动词："+key.substring("EXCEPTION_VERB:".length());if(key.equals("SURU_COMPOUND"))return"する复合动词";if(key.equals("KURU_READING_CHANGE"))return"来る的读音变化";return"活用规则";}
 private Map<String,Map<String,Object>>rates(List<TrainingQuestion>x,java.util.function.Function<TrainingQuestion,String>key){Map<String,List<TrainingQuestion>>g=x.stream().collect(Collectors.groupingBy(key));Map<String,Map<String,Object>>out=new TreeMap<>();g.forEach((k,v)->{long c=v.stream().filter(q->Boolean.TRUE.equals(q.correct)).count();out.put(k,Map.of("attempts",v.size(),"correct",c,"accuracy",Math.round(c*1000.0/v.size())/10.0));});return out;}
 private String normalize(String s){return s==null?"":s.strip().replace(" ","").replace("　","");}
 private String classifyMistake(TrainingQuestion q,String answer){if(q.conjugationType==ConjugationType.POLITE&&answer.equals(normalize(q.dictionaryForm+"ます")))return"DIRECT_ADD_MASU";if(q.conjugationType==ConjugationType.TE&&answer.endsWith("みて"))return"WRONG_TE_ENDING_RULE";return"CONJUGATION_FORM_ERROR";}
 private List<String>parseList(String s){try{return s==null?List.of():json.readValue(s,new TypeReference<>(){});}catch(Exception e){return List.of();}}
 private List<Map<String,String>>parseReasons(String s){try{return json.readValue(s,new TypeReference<>(){});}catch(Exception e){return List.of();}}
}
