package com.verbtrainer.api;
import com.fasterxml.jackson.databind.*;import com.verbtrainer.VerbTrainerApplication;import com.verbtrainer.conjugation.VerbClass;import com.verbtrainer.dictionary.*;import com.verbtrainer.smart.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest(classes=VerbTrainerApplication.class)@AutoConfigureMockMvc class SmartTrainingApiTest{
 @Autowired MockMvc mvc;@Autowired VerbRepository verbs;@Autowired ObjectMapper json;@Autowired TrainingQuestionRepository questions;@Autowired TrainingSessionRepository sessions;
 @BeforeEach void seed(){questions.deleteAll();sessions.deleteAll();classify("食べる","たべる",VerbClass.ICHIDAN,JlptLevel.N5,1);classify("勉強","べんきょう",VerbClass.SURU,JlptLevel.N5,10);classify("冷める","さめる",VerbClass.ICHIDAN,JlptLevel.N5,80);classify("読む","よむ",VerbClass.GODAN,JlptLevel.N4,1);classify("選ぶ","えらぶ",VerbClass.GODAN,JlptLevel.N3,1);classify("防ぐ","ふせぐ",VerbClass.GODAN,JlptLevel.N2,1);classify("未分類","みぶんるい",VerbClass.ICHIDAN,null,null);}
 private void classify(String word,String reading,VerbClass verbClass,JlptLevel level,Integer rank){var v=verbs.findByLemmaAndReading(word,reading).stream().findFirst().orElseGet(()->verbs.save(new VerbEntry(word,reading,"测试",verbClass,"test")));v.jlptLevel=level;v.commonRank=rank;verbs.save(v);}
 String body(String level,int count,String mode,String conjugations){return "{\"jlptLevel\":\""+level+"\",\"questionCount\":"+count+",\"mode\":\""+mode+"\",\"questionTypes\":[\"DICTIONARY_TO_CONJUGATION\"],\"conjugationTypes\":"+conjugations+",\"prioritizeWeakness\":true,\"prioritizeDueReview\":true,\"includeNewWords\":true,\"commonWordsOnly\":true,\"showReading\":true,\"aiEnhancementEnabled\":true}";}
 @Test void createDoesNotLeakAnswerAndCanSubmit()throws Exception{var response=mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N4",10,"SMART","[\"TE\",\"PAST\"]"))).andExpect(status().isOk()).andExpect(jsonPath("$.questions[0].correctAnswer").doesNotExist()).andExpect(jsonPath("$.questions[0].displayName").isNotEmpty()).andExpect(jsonPath("$.questions[0].displayName").value(org.hamcrest.Matchers.not(org.hamcrest.Matchers.anyOf(org.hamcrest.Matchers.is("TE"),org.hamcrest.Matchers.is("PAST"))))).andExpect(jsonPath("$.questions[0].prompt").value(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString(" TE")))).andReturn().getResponse().getContentAsString();JsonNode root=json.readTree(response);long sid=root.get("sessionId").asLong(),qid=root.at("/questions/0/questionId").asLong();mvc.perform(post("/api/v1/training/sessions/"+sid+"/questions/"+qid+"/answer").contentType("application/json").content("{\"answer\":\"错误\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.correct").value(false)).andExpect(jsonPath("$.displayName").isNotEmpty()).andExpect(jsonPath("$.change").isNotEmpty()).andExpect(jsonPath("$.steps").isArray()).andExpect(jsonPath("$.knowledgePointsUpdated").isArray());mvc.perform(post("/api/v1/training/sessions/"+sid+"/questions/"+qid+"/answer").contentType("application/json").content("{\"answer\":\"错误\"}")).andExpect(status().isConflict());mvc.perform(get("/api/v1/training/sessions/"+sid+"/summary")).andExpect(status().isOk()).andExpect(jsonPath("$.completedCount").value(1)).andExpect(jsonPath("$.byConjugationType.TE").doesNotExist()).andExpect(jsonPath("$.byConjugationType.PAST").doesNotExist());}
 @Test void policyProvidesFriendlyLabels()throws Exception{mvc.perform(get("/api/v1/training/sessions/policy/N5")).andExpect(status().isOk()).andExpect(jsonPath("$.conjugationLabels[?(@.type == 'POLITE')].displayName").value("ます形（礼貌表达）")).andExpect(jsonPath("$.conjugationLabels[?(@.type == 'TE')].chineseName").value("て形"));}
 @Test void rejectsInvalidCountAndOutOfLevelConjugation()throws Exception{mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N4",11,"SMART","[\"TE\"]"))).andExpect(status().isBadRequest());mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N5",10,"SMART","[\"CAUSATIVE_PASSIVE\"]"))).andExpect(status().isBadRequest());}
 @Test void eachLevelUsesOnlyItsOwnVocabulary()throws Exception{assertOnlyLevel("N5",org.hamcrest.Matchers.anyOf(org.hamcrest.Matchers.is("食べる"),org.hamcrest.Matchers.is("勉強する"),org.hamcrest.Matchers.is("冷める")));assertOnlyLevel("N4",org.hamcrest.Matchers.is("読む"));assertOnlyLevel("N3",org.hamcrest.Matchers.is("選ぶ"));assertOnlyLevel("N2",org.hamcrest.Matchers.is("防ぐ"));}
 @Test void newLearnerGetsCommonWordsFirst()throws Exception{mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N5",10,"SMART","[\"TE\"]"))).andExpect(status().isOk()).andExpect(jsonPath("$.questions[0].dictionaryForm").value("食べる"));}
 @Test void baseSuruEntryIsDisplayedAndConjugatedAsFullVerb()throws Exception{mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N5",10,"SMART","[\"TE\"]"))).andExpect(status().isOk()).andExpect(jsonPath("$.questions[*].dictionaryForm").value(org.hamcrest.Matchers.hasItem("勉強する")));}
 private void assertOnlyLevel(String level,org.hamcrest.Matcher<String> expected)throws Exception{mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body(level,10,"SMART","[\"TE\"]"))).andExpect(status().isOk()).andExpect(jsonPath("$.questions[*].dictionaryForm").value(org.hamcrest.Matchers.everyItem(expected))).andExpect(jsonPath("$.questions[*].dictionaryForm").value(org.hamcrest.Matchers.not(org.hamcrest.Matchers.hasItem("未分類")))).andExpect(jsonPath("$.questions[0].correctAnswer").doesNotExist());}
}
