package com.verbtrainer.api;
import com.fasterxml.jackson.databind.*;import com.verbtrainer.VerbTrainerApplication;import com.verbtrainer.conjugation.VerbClass;import com.verbtrainer.dictionary.*;import com.verbtrainer.smart.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest(classes=VerbTrainerApplication.class)@AutoConfigureMockMvc class SmartTrainingApiTest{
 @Autowired MockMvc mvc;@Autowired VerbRepository verbs;@Autowired JlptVocabularyRepository levels;@Autowired ObjectMapper json;
 @BeforeEach void seed(){if(verbs.findFirstByLemma("読む").isEmpty()){var v=verbs.save(new VerbEntry("読む","よむ","读",VerbClass.GODAN,"v5m"));levels.save(new JlptVocabularyLevel(v.id,JlptLevel.N4,JlptLevelSource.SEED_DATA,DataConfidence.HIGH));}}
 String body(String level,int count,String mode,String conjugations){return "{\"jlptLevel\":\""+level+"\",\"questionCount\":"+count+",\"mode\":\""+mode+"\",\"questionTypes\":[\"DICTIONARY_TO_CONJUGATION\"],\"conjugationTypes\":"+conjugations+",\"prioritizeWeakness\":true,\"prioritizeDueReview\":true,\"includeNewWords\":true,\"commonWordsOnly\":true,\"showReading\":true,\"aiEnhancementEnabled\":true}";}
 @Test void createDoesNotLeakAnswerAndCanSubmit()throws Exception{var response=mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N4",10,"SMART","[\"TE\",\"PAST\"]"))).andExpect(status().isOk()).andExpect(jsonPath("$.questions[0].correctAnswer").doesNotExist()).andReturn().getResponse().getContentAsString();JsonNode root=json.readTree(response);long sid=root.get("sessionId").asLong(),qid=root.at("/questions/0/questionId").asLong();mvc.perform(post("/api/v1/training/sessions/"+sid+"/questions/"+qid+"/answer").contentType("application/json").content("{\"answer\":\"错误\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.correct").value(false)).andExpect(jsonPath("$.knowledgePointsUpdated").isArray());mvc.perform(post("/api/v1/training/sessions/"+sid+"/questions/"+qid+"/answer").contentType("application/json").content("{\"answer\":\"错误\"}")).andExpect(status().isConflict());mvc.perform(get("/api/v1/training/sessions/"+sid+"/summary")).andExpect(status().isOk()).andExpect(jsonPath("$.completedCount").value(1));}
 @Test void rejectsInvalidCountAndOutOfLevelConjugation()throws Exception{mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N4",11,"SMART","[\"TE\"]"))).andExpect(status().isBadRequest());mvc.perform(post("/api/v1/training/sessions").contentType("application/json").content(body("N5",10,"SMART","[\"CAUSATIVE_PASSIVE\"]"))).andExpect(status().isBadRequest());}
}
