<script setup lang="ts">
import{ref,computed,onMounted}from'vue';import{api}from'../services/api';import{ElMessage}from'element-plus';
type Mode='FULL'|'CATEGORY'|'RULE';type Stage='CATEGORY'|'RULE'|'CONJUGATION';
const mode=ref<Mode>('FULL'),phase=ref<'config'|'training'|'done'>('config'),question=ref<any>(),stage=ref<Stage>('CATEGORY'),answer=ref(''),result=ref<any>(),completed=ref(0),correct=ref(0),used=ref<number[]>([]),stats=ref<any>({category:{accuracy:0},rule:{accuracy:0},conjugation:{accuracy:0}}),loading=ref(false);
const stageName=computed(()=>stage.value==='CATEGORY'?'识别动词类别':stage.value==='RULE'?'判断て形规则':'完成て形');
const prompt=computed(()=>stage.value==='CATEGORY'?`「${question.value?.word}」是什么类型的动词？`:stage.value==='RULE'?`「${question.value?.word}」的て形使用哪条规则？`:`请输入「${question.value?.word}」的て形。`);
const options=computed(()=>stage.value==='CATEGORY'?question.value?.categoryOptions:stage.value==='RULE'?question.value?.ruleOptions:[]);
async function loadStats(){stats.value=(await api.get('/v1/rule-training/stats')).data}
async function start(){used.value=[];completed.value=0;correct.value=0;phase.value='training';await nextQuestion()}
async function nextQuestion(){loading.value=true;try{question.value=(await api.post('/v1/rule-training/question',{mode:mode.value,excludeVerbIds:used.value})).data;used.value.push(question.value.verbId);stage.value=mode.value==='RULE'?'RULE':'CATEGORY';answer.value='';result.value=undefined}catch(e:any){ElMessage.error(e.response?.data?.error||'规则题创建失败')}finally{loading.value=false}}
async function submit(){if(!answer.value.trim())return;result.value=(await api.post('/v1/rule-training/answer',{verbId:question.value.verbId,stage:stage.value,answer:answer.value})).data;if(result.value.correct)correct.value++}
async function advance(){if(mode.value==='FULL'&&stage.value!=='CONJUGATION'){stage.value=stage.value==='CATEGORY'?'RULE':'CONJUGATION';answer.value='';result.value=undefined;return}completed.value++;if(completed.value>=10){phase.value='done';await loadStats()}else await nextQuestion()}
onMounted(loadStats);
</script>
<template>
<template v-if="phase==='config'"><div class="eyebrow">N5 RULE TRAINING</div><h1 class="page-title">先识别，再判断规则，最后完成变化。</h1><div class="grid rule-stats"><div class="card stat"><span>动词分类正确率</span><strong>{{stats.category.accuracy}}%</strong></div><div class="card stat"><span>规则判定正确率</span><strong>{{stats.rule.accuracy}}%</strong></div><div class="card stat"><span>实际变形正确率</span><strong>{{stats.conjugation.accuracy}}%</strong></div></div><div class="card mode-card"><h3>选择训练方式</h3><el-radio-group v-model="mode"><el-radio-button value="FULL">规则训练（完整三步）</el-radio-button><el-radio-button value="CATEGORY">动词分类训练</el-radio-button><el-radio-button value="RULE">规则判定训练</el-radio-button></el-radio-group><p class="muted">每轮 10 个 N5 常用动词。薄弱规则优先，答案由本地规则引擎计算。</p><el-button class="primary" type="primary" size="large" @click="start">开始规则训练</el-button></div></template>
<template v-else-if="phase==='training'&&question"><div class="hero"><div><div class="eyebrow">N5 规则训练 · {{stageName}}</div><h1 class="page-title">第 {{completed+1}} / 10 个动词</h1></div><el-progress type="circle" :percentage="Math.round(completed/10*100)" :width="62"/></div><div class="card practice" v-loading="loading"><span class="tag">{{stageName}}</span><div class="question-word">{{question.word}}</div><p class="muted">{{question.reading}}</p><h3>{{prompt}}</h3><el-radio-group v-if="options?.length" v-model="answer" class="rule-options"><el-radio v-for="o in options" :key="o" :value="o" border>{{o}}</el-radio></el-radio-group><el-input v-else v-model="answer" class="answer-input" size="large" @keyup.enter="result?advance():submit()"/><div class="actions"><el-button v-if="!result" class="primary" type="primary" @click="submit">确认</el-button><el-button v-else @click="advance">{{mode==='FULL'&&stage!=='CONJUGATION'?'进入下一步':'下一个动词'}}</el-button></div><div v-if="result" class="result-box" :class="result.correct?'ok':'wrong'"><h3>{{result.correct?'回答正确':'正确答案：'+result.correctAnswer}}</h3><p>{{result.explanation}}</p><p><b>变化：</b>{{question.word}} → {{result.conjugation}}</p><p><b>当前知识点：</b>{{result.rule}}</p><div class="examples"><span v-for="x in result.examples" :key="x">{{x}}</span></div></div></div></template>
<template v-else><div class="eyebrow">规则训练完成</div><h1 class="page-title">本轮完成：{{correct}} 次步骤判断正确</h1><div class="grid rule-stats"><div class="card stat"><span>分类</span><strong>{{stats.category.accuracy}}%</strong></div><div class="card stat"><span>规则</span><strong>{{stats.rule.accuracy}}%</strong></div><div class="card stat"><span>变形</span><strong>{{stats.conjugation.accuracy}}%</strong></div></div><el-button class="primary" type="primary" @click="phase='config'">再练一轮</el-button></template>
</template>
<style scoped>.rule-stats{margin:24px 0}.mode-card{max-width:850px}.mode-card p{line-height:1.8}.rule-options{display:grid;grid-template-columns:1fr 1fr;gap:10px;text-align:left;max-width:680px;margin:auto}.rule-options .el-radio{margin:0;height:auto;min-height:44px}.actions{margin-top:22px}.examples{display:flex;gap:8px;flex-wrap:wrap}.examples span{background:#fff;padding:7px 10px;border-radius:7px}@media(max-width:600px){.rule-options{grid-template-columns:1fr}.mode-card .el-radio-group{display:grid}}</style>
