<script setup lang="ts">
import{ref,computed,onMounted,onBeforeUnmount,watch}from'vue';import{useRoute}from'vue-router';import{api}from'../services/api';import{ElMessage}from'element-plus';
type Level='N5'|'N4'|'N3'|'N2';type FormLabel={type:string;japaneseName:string;chineseName:string;displayName:string;explanation:string};type Q={questionId:number;questionType:string;dictionaryForm:string;reading?:string;conjugationType:string;japaneseName:string;chineseName:string;displayName:string;labelExplanation:string;prompt:string;options:string[];selectionReasons:{code:string;messageZh:string}[]};
const defaults:Record<Level,string[]>={N5:['POLITE','POLITE_NEGATIVE','POLITE_PAST','POLITE_PAST_NEGATIVE','NAI','TE','PAST','DESIDERATIVE_TAI'],N4:['POLITE','POLITE_NEGATIVE','POLITE_PAST','NAI','TE','PAST','DESIDERATIVE_TAI','VOLITIONAL','POTENTIAL','CONDITIONAL_BA','CONDITIONAL_TARA','PROHIBITIVE','IMPERATIVE'],N3:['POLITE','NAI','TE','PAST','POTENTIAL','PASSIVE','CAUSATIVE','CAUSATIVE_PASSIVE','CONDITIONAL_BA'],N2:['POLITE','POLITE_NEGATIVE','POLITE_PAST','POLITE_PAST_NEGATIVE','NAI','PAST','TE','POTENTIAL','PASSIVE','CAUSATIVE','CAUSATIVE_PASSIVE','VOLITIONAL','IMPERATIVE','CONDITIONAL_BA','CONDITIONAL_TARA','DESIDERATIVE_TAI','PROHIBITIVE']};
const levelText:Record<Level,string>={N5:'练习 N5 常用动词',N4:'练习 N4 常用动词',N3:'练习 N3 常用动词',N2:'练习 N2 常用动词'};
const allQ=['DICTIONARY_TO_CONJUGATION','CONJUGATION_TO_DICTIONARY','VERB_CLASS','MULTIPLE_CHOICE_CONJUGATION','TRUE_FALSE','CONTEXT_SELECTION'],allC=defaults.N2;
const stored=localStorage.getItem('smartTrainingConfig');const config=ref<any>(stored?JSON.parse(stored):{jlptLevel:'N5',questionCount:10,mode:'SMART',questionTypes:['DICTIONARY_TO_CONJUGATION','MULTIPLE_CHOICE_CONJUGATION','TRUE_FALSE'],conjugationTypes:defaults.N5,prioritizeWeakness:true,prioritizeDueReview:true,includeNewWords:true,commonWordsOnly:true,showReading:true,autoExplain:true,aiEnhancementEnabled:false});
const route=useRoute(),selectedPoint=ref<any>();
watch(config,v=>localStorage.setItem('smartTrainingConfig',JSON.stringify(v)),{deep:true});watch(()=>config.value.jlptLevel,(l:Level)=>{if(config.value.mode!=='CUSTOM')config.value.conjugationTypes=[...defaults[l]]});
const phase=ref<'config'|'session'|'summary'>('config'),session=ref<any>(),idx=ref(0),answer=ref(''),result=ref<any>(),summary=ref<any>(),hint=ref(false),loading=ref(false),aiText=ref(''),formLabels=ref<Record<string,FormLabel>>({});const current=computed<Q|undefined>(()=>session.value?.questions[idx.value]);const formName=(type:string)=>formLabels.value[type]?.chineseName||'活用形式';
async function start(){loading.value=true;try{session.value=(await api.post('/v1/training/sessions',config.value)).data;idx.value=0;answer.value='';result.value=undefined;phase.value='session';if(session.value.actualCount<session.value.requestedCount)ElMessage.warning(session.value.shortageReason)}catch(e:any){ElMessage.error(e.response?.data?.error||'训练创建失败')}finally{loading.value=false}}
async function submit(){if(!answer.value.trim())return;try{result.value=(await api.post(`/v1/training/sessions/${session.value.sessionId}/questions/${current.value!.questionId}/answer`,{answer:answer.value})).data}catch(e:any){ElMessage.error(e.response?.data?.error||'提交失败')}}
async function next(){if(idx.value<session.value.questions.length-1){idx.value++;answer.value='';result.value=undefined;hint.value=false;aiText.value=''}else{summary.value=(await api.get(`/v1/training/sessions/${session.value.sessionId}/summary`)).data;phase.value='summary'}}
async function explain(){if(!result.value)return ElMessage.info('提交答案后可调用解释');aiText.value=(await api.post('/ai/explain',{lemma:current.value!.dictionaryForm,form:current.value!.chineseName,correct:result.value.correctAnswer,attempt:answer.value})).data.explanation}
function key(e:KeyboardEvent){if(phase.value!=='session')return;if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();explain()}else if(e.key==='Tab'){e.preventDefault();hint.value=true}else if(e.code==='Space'&&result.value){e.preventDefault();next()}}onMounted(async()=>{window.addEventListener('keydown',key);try{const data=(await api.get('/v1/training/sessions/policy/N2')).data;formLabels.value=Object.fromEntries(data.conjugationLabels.map((x:FormLabel)=>[x.type,x]));if(route.query.knowledgePoint){selectedPoint.value=(await api.get(`/v1/knowledge-points/${route.query.knowledgePoint}`)).data;config.value.jlptLevel=selectedPoint.value.jlptLevel;config.value.questionCount=20;config.value.mode='SMART';config.value.questionTypes=['DICTIONARY_TO_CONJUGATION'];config.value.conjugationTypes=[selectedPoint.value.conjugationType];config.value.knowledgePointCode=selectedPoint.value.code}}catch{ElMessage.warning('训练配置加载失败，请刷新页面')}});onBeforeUnmount(()=>window.removeEventListener('keydown',key));
const labels:Record<string,string>={SMART:'智能推荐',RANDOM:'等级随机',WRONG_ONLY:'只练错题',DUE_REVIEW:'到期复习',NEW_WORDS:'当前等级新词',CUSTOM:'自定义专项',DICTIONARY_TO_CONJUGATION:'原形 → 活用',CONJUGATION_TO_DICTIONARY:'活用 → 原形',VERB_CLASS:'类别判断',MULTIPLE_CHOICE_CONJUGATION:'活用选择',TRUE_FALSE:'判断题',CONTEXT_SELECTION:'语境选择'};
</script>
<template>
<template v-if="phase==='config'"><div class="eyebrow">智能训练配置</div><h1 class="page-title">按你的等级与薄弱点组一份练习。</h1><div class="config-layout"><section class="card"><h3>1. JLPT 等级</h3><div class="level-cards"><button v-for="l in ['N5','N4','N3','N2']" :key="l" :class="{active:config.jlptLevel===l}" @click="config.jlptLevel=l">{{l}}<small>{{levelText[l as Level]}}</small></button></div><el-alert :title="levelText[config.jlptLevel as Level]" type="info" :closable="false"/><h3>2. 题目数量</h3><el-radio-group v-model="config.questionCount"><el-radio-button v-for="n in [10,20,30,50]" :key="n" :value="n">{{n}} 题</el-radio-button></el-radio-group><h3>3. 训练模式</h3><el-select v-model="config.mode" style="width:100%"><el-option v-for="m in ['SMART','RANDOM','WRONG_ONLY','DUE_REVIEW','NEW_WORDS','CUSTOM']" :key="m" :label="labels[m]" :value="m"/></el-select><h3>4. 题型</h3><el-checkbox-group v-model="config.questionTypes" class="check-grid"><el-checkbox v-for="t in allQ" :key="t" :value="t">{{labels[t]}}</el-checkbox></el-checkbox-group><h3>5. 活用范围</h3><el-checkbox-group v-model="config.conjugationTypes" class="check-grid"><el-checkbox v-for="t in allC" :key="t" :value="t" :disabled="config.mode!=='CUSTOM'&&!defaults[config.jlptLevel as Level].includes(t)">{{formName(t)}}</el-checkbox></el-checkbox-group></section><aside class="card options-panel"><h3>附加选项</h3><el-switch v-model="config.prioritizeWeakness" active-text="优先薄弱项"/><el-switch v-model="config.prioritizeDueReview" active-text="优先到期复习"/><el-switch v-model="config.includeNewWords" active-text="包含新词"/><el-switch v-model="config.commonWordsOnly" active-text="只使用常用词"/><el-switch v-model="config.showReading" active-text="显示假名"/><el-switch v-model="config.autoExplain" active-text="答错显示规则"/><el-switch v-model="config.aiEnhancementEnabled" active-text="允许 AI 增强题干"/><el-button class="primary start-button" type="primary" size="large" :loading="loading" @click="start">开始智能训练</el-button><small class="muted">AI 不可用时自动使用本地题目。</small></aside></div></template>
<template v-else-if="phase==='session'&&current"><div class="hero"><div><div class="eyebrow">{{session.jlptLevel}} 常用动词训练 · {{labels[session.mode]}}</div><h1 class="page-title">第 {{idx+1}} / {{session.actualCount}} 题</h1></div><el-progress type="circle" :percentage="Math.round((idx+1)/session.actualCount*100)" :width="62"/></div><div class="card practice"><span class="tag">{{labels[current.questionType]}}</span><div class="question-word">{{current.dictionaryForm}}</div><p v-if="current.reading" class="muted">{{current.reading}}</p><h3>{{current.prompt}}</h3><el-radio-group v-if="current.options?.length" v-model="answer" class="answer-options"><el-radio-button v-for="o in current.options" :key="o" :value="o">{{o}}</el-radio-button></el-radio-group><el-input v-else v-model="answer" class="answer-input" size="large" autofocus @keyup.enter="result?next():submit()"/><p v-if="hint" class="hint">提示：目标活用是「{{current.displayName}}」。</p><div style="margin-top:20px"><el-button v-if="!result" class="primary" type="primary" size="large" @click="submit">确认答案</el-button><el-button v-else size="large" @click="next">下一题</el-button></div><div v-if="result" class="result-box" :class="result.correct?'ok':'wrong'"><h3>{{result.correct?'回答正确':'正确答案：'+result.correctAnswer}}</h3><p><b>变化：</b>{{result.change}}</p><p><b>类型：</b>{{result.chineseName}}</p><p><b>规则：</b>{{result.explanation}}</p><el-collapse><el-collapse-item title="查看变化步骤"><p v-for="step in result.steps" :key="step">{{step}}</p></el-collapse-item><el-collapse-item title="为什么推荐这道题"><p v-for="r in current.selectionReasons" :key="r.code">{{r.messageZh}}</p></el-collapse-item></el-collapse><el-button text @click="explain">AI 进一步解释（Ctrl + Enter）</el-button><p v-if="aiText" class="ai-text">{{aiText}}</p></div></div></template>
<template v-else><div class="eyebrow">训练总结</div><h1 class="page-title">{{summary.jlptLevel}} 本轮完成</h1><div class="grid" style="margin-top:24px"><div class="card stat"><span>正确率</span><strong>{{summary.accuracy}}%</strong></div><div class="card stat"><span>完成</span><strong>{{summary.completedCount}} / {{summary.totalQuestions}}</strong></div><div class="card stat"><span>正确</span><strong>{{summary.correctCount}}</strong></div></div><div class="summary-grid"><div class="card"><h3>薄弱知识点</h3><p v-for="k in summary.weakestKnowledgePoints" :key="k" class="knowledge-pill">{{k}}</p></div><div class="card"><h3>错误动词</h3><p>{{summary.wrongVerbs.join('、')||'无'}}</p><h3>下一轮建议</h3><p>{{summary.recommendation}}</p></div></div><el-button class="primary" type="primary" size="large" @click="phase='config'">配置下一轮</el-button></template>
</template>
